apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frappe-app1
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: frappe-app1
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: erpnext
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated: 
       prune: true
       selfHeal: true